INDICATOR_LABELS: dict[str, str] = {
    "success_rate": "Taux de réussite",
    "attendance_rate": "Taux de présence",
    "dropout_rate": "Taux d'abandon",
    "repetition_rate": "Taux de redoublement",
    "budget_allocated": "Budget alloué",
    "budget_consumed": "Budget consommé",
    "budget_execution_rate": "Taux d'exécution budgétaire",
    "cost_per_student": "Coût par étudiant",
    "teaching_headcount": "Effectif enseignant",
    "admin_headcount": "Effectif administratif",
    "absenteeism_rate": "Taux d'absentéisme",
    "training_hours": "Heures de formation",
    "energy_consumption_kwh": "Consommation énergétique (kWh)",
    "carbon_footprint_ton": "Empreinte carbone (tonnes CO₂)",
    "recycling_rate": "Taux de recyclage",
    "employability_rate": "Taux d'employabilité",
    "national_convention_rate": "Taux de convention nationale",
    "international_convention_rate": "Taux de convention internationale",
    "insertion_delay_months": "Délai d'insertion (mois)",
    "publications_count": "Nombre de publications",
    "active_projects": "Projets de recherche actifs",
    "funding_tnd": "Financements obtenus (TND)",
}
